### ISSUE TITLE
Showing twice as many stars as it should

### ISSUE THREAD

**Issue by ksouthworth** [KarthiPnsmy/Ratingbar#1]
rating: 2
stars: 10
stepSize: 1
indicator: false

It's showing the bar with 4 stars selected!

**Comment by KarthiPnsmy** [comment]
@ksouthworth thanks for reporting issue. i will look into it.

**Comment by KarthiPnsmy** [comment]
@ksouthworth Issue which you reported was fixed. Please pull the latest code and test it in your end. Still if you are facing any problem let me know.
